//! `flotop --snapshot` — generate a Markdown report from the current
//! state of the local box (and any remote hosts) and exit.
//!
//! The output is intentionally pasteable into:
//!   * a GitHub issue
//!   * an HN comment
//!   * a Slack DM to a coworker
//!   * an incident postmortem doc
//!
//! `--anonymize` swaps real hostnames for `host1`, `host2`, etc. so
//! you can share triage data without leaking infrastructure naming.
//! That's the feature that makes `--snapshot` actually get shared,
//! which is the entire distribution mechanism for the v0.1 launch.
//!
//! For now this is a sync entry point that operates on a list of host
//! names + their (possibly empty) collected vitals. The full async
//! "go connect to all hosts and gather snapshots" path is invoked from
//! main.rs.

use crate::collectors::remote::RemoteSnapshot;

/// One host's contribution to the snapshot. `vitals` may be `None`
/// when the connection failed — in that case `error` is shown instead.
#[derive(Debug, Clone)]
pub struct HostSnapshotInput {
    pub display_name: String,
    pub data: Result<RemoteSnapshot, String>,
}

/// Render a complete Markdown report. If `anonymize` is true, host
/// display names are replaced with host1, host2, … in the order they
/// appear in `inputs`.
pub fn render_snapshot_markdown(inputs: &[HostSnapshotInput], anonymize: bool) -> String {
    let mut out = String::new();
    out.push_str("# flotop snapshot\n\n");
    out.push_str(&format!(
        "Generated {} • {} host{}\n\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S %Z"),
        inputs.len(),
        if inputs.len() == 1 { "" } else { "s" }
    ));

    for (i, input) in inputs.iter().enumerate() {
        let display = if anonymize {
            format!("host{}", i + 1)
        } else {
            input.display_name.clone()
        };
        out.push_str(&format!("## {}\n\n", display));

        match &input.data {
            Ok(snap) => render_host_section(&mut out, snap),
            Err(e) => {
                out.push_str(&format!("**Status:** UNREACHABLE\n\n```\n{}\n```\n\n", e));
            }
        }
    }

    out.push_str("---\n\n");
    out.push_str(
        "_Generated by [flotop](https://github.com/rshzrh/flotop) — \
         a TUI for triaging your fleet at 2am._\n",
    );
    out
}

fn render_host_section(out: &mut String, snap: &RemoteSnapshot) {
    out.push_str("**Status:** UP\n\n");

    if let Some(load) = snap.loadavg {
        out.push_str(&format!(
            "- **Load avg:** {:.2} {:.2} {:.2}\n",
            load.one, load.five, load.fifteen
        ));
    }

    if snap.mem.total > 0 {
        let used_gb = snap.mem.used() as f64 / 1e9;
        let total_gb = snap.mem.total as f64 / 1e9;
        let pct = if snap.mem.total > 0 {
            snap.mem.used() as f64 / snap.mem.total as f64 * 100.0
        } else {
            0.0
        };
        out.push_str(&format!(
            "- **Memory:** {:.1} GB / {:.1} GB ({:.0}%)\n",
            used_gb, total_gb, pct
        ));
    }

    if let Some(b) = snap.busiest_disk {
        out.push_str(&format!("- **Busiest disk:** {:.0}% busy\n", b.busy_pct));
    }

    out.push_str(&format!(
        "- **TCP connections:** {} established / {} time-wait\n",
        snap.ss.established, snap.ss.time_wait
    ));

    if let Some(c) = snap.ctxt_total {
        out.push_str(&format!("- **Context switches (lifetime):** {}\n", c));
    }

    if !snap.top_processes.is_empty() {
        out.push_str("\n### Top processes (by CPU)\n\n");
        out.push_str("| User | PID | %CPU | %MEM | Command |\n");
        out.push_str("|------|-----|------|------|---------|\n");
        for p in snap.top_processes.iter().take(10) {
            // Sanitize command (escape pipe chars for markdown table).
            let cmd = p.command.replace('|', "\\|");
            out.push_str(&format!(
                "| {} | {} | {:.1} | {:.1} | {} |\n",
                p.user, p.pid, p.cpu_pct, p.mem_pct, cmd
            ));
        }
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::collectors::parsers::{LoadAvg, ParsedMemInfo, PsRow, SsSummary};
    use crate::collectors::remote::BusiestDisk;

    fn sample_snap() -> RemoteSnapshot {
        RemoteSnapshot {
            loadavg: Some(LoadAvg {
                one: 0.42,
                five: 0.31,
                fifteen: 0.28,
            }),
            mem: ParsedMemInfo {
                total: 16_000_000_000,
                free: 4_000_000_000,
                available: 8_000_000_000,
                swap_total: 0,
                swap_free: 0,
            },
            ss: SsSummary {
                established: 87,
                time_wait: 134,
                tcp_total: 234,
            },
            top_processes: vec![PsRow {
                user: "postgres".into(),
                pid: 1234,
                cpu_pct: 87.5,
                mem_pct: 4.2,
                rss_kb: 345678,
                command: "postgres: writer".into(),
            }],
            busiest_disk: Some(BusiestDisk {
                busy_pct: 42.0,
                io_ticks: 99999,
            }),
            interfaces: vec![],
            ctxt_total: Some(9876543210),
        }
    }

    // ── 1: anonymize replaces real hostnames with host1, host2, … ──
    #[test]
    fn anonymize_replaces_real_hostnames() {
        let inputs = vec![
            HostSnapshotInput {
                display_name: "prod-web-01.example.com".into(),
                data: Ok(sample_snap()),
            },
            HostSnapshotInput {
                display_name: "prod-db-01.example.com".into(),
                data: Ok(sample_snap()),
            },
        ];
        let md = render_snapshot_markdown(&inputs, true);
        // Real hostnames must NOT appear in the output.
        assert!(
            !md.contains("prod-web-01"),
            "anonymize failed: leaked prod-web-01"
        );
        assert!(
            !md.contains("prod-db-01"),
            "anonymize failed: leaked prod-db-01"
        );
        assert!(md.contains("host1"));
        assert!(md.contains("host2"));
    }

    // ── 2: non-anonymized output keeps real names ──
    #[test]
    fn non_anonymized_output_keeps_real_names() {
        let inputs = vec![HostSnapshotInput {
            display_name: "myhost.local".into(),
            data: Ok(sample_snap()),
        }];
        let md = render_snapshot_markdown(&inputs, false);
        assert!(md.contains("myhost.local"));
    }

    // ── 3: failed-host snapshot includes the error ──
    #[test]
    fn failed_host_snapshot_shows_unreachable_with_error() {
        let inputs = vec![HostSnapshotInput {
            display_name: "down-box".into(),
            data: Err("Auth failed: bad key".into()),
        }];
        let md = render_snapshot_markdown(&inputs, false);
        assert!(md.contains("UNREACHABLE"));
        assert!(md.contains("Auth failed: bad key"));
    }

    // ── 4: pipe characters in command are escaped for markdown table ──
    #[test]
    fn pipe_chars_in_command_are_escaped() {
        let mut snap = sample_snap();
        snap.top_processes[0].command = "ps aux | grep postgres".into();
        let inputs = vec![HostSnapshotInput {
            display_name: "box".into(),
            data: Ok(snap),
        }];
        let md = render_snapshot_markdown(&inputs, false);
        assert!(md.contains("ps aux \\| grep postgres"));
        assert!(!md.contains("ps aux | grep postgres"));
    }
}
